# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python code checks

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint ruff black bandit pytype
    - name: Run Pylint
      run: pylint
      continue-on-error: true
    - name: Run Ruff
      run: ruff .
      continue-on-error: true

    - name: Run Black
      run: black .
      continue-on-error: true

    - name: Run Bandit
      run: bandit -r .
      continue-on-error: true

    - name: Run Pytype
      run: pytype .
      continue-on-error: true

