name: Python Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff black bandit pytype
    - name: Run Pylint
      if: always()
      run: |
        pylint $(git ls-files '*.py')
    - name: Run Ruff
      if: always()
      run: |
        ruff $(git ls-files '*.py')
    - name: Run Black
      if: always()
      run: |
        black --diff --color $(git ls-files '*.py')
    - name: Run Bandit
      if: always()
      run: |
        bandit $(git ls-files '*.py')
    - name: Run Pytype
      if: always()
      run: |
        pytype $(git ls-files '*.py')
